#define SOIL_MOISTURE_TOPIC_SUFFIX "soil_moisture_sensor/soil_moisture"
#define TEMPERATURE_TOPIC_SUFFIX "temperature_sensor/temperature"
#define WATER_PUMP_TOPIC_SUFFIX "water_pump/activate"
#define LIGHT_SENSOR_TOPIC_SUFFIX "light_sensor/light"
#define LIGHT_EMITTER_TOPIC_SUFFIX "light_emitter/activate"